### PR TITLE
ft(social-auth): Users should be able to Login with Google and Facebook

### PR DESCRIPTION
**Pull request by Francoise02**
### What does this PR do?
Users should be able to Login to Barefoot Nomad using Google or Facebook.

### How should this be manually tested?

1. Run `yarn ` to install all the required packages for this PR
2. Run `yarn start` 
3. To the landing page, click the login link and you will get the login form 
4. Click to login with Google or Facebook

### What are the relevant pivotal tracker stories?
[#182201527](https://www.pivotaltracker.com/story/show/182201527)

### CODE REVIEW

**Comment by ericus123** [comment]
@Francoise02 needs rebase

**Comment by ericus123** [comment]
@Francoise02 why is this not rebased

**Comment by Francoise02** [comment]
> @Francoise02 why is this not rebased

@ericus123 Done

**Comment by didasmbalanya** [comment]
Seems to work fine. Just make sure the authentication routes are protected after a successful login

**Review by didasmbalanya — APPROVED** [review]

**Pull request merged**
