### PR TITLE
Reset password #182201525

### PR DESCRIPTION
**Pull request by uwishema11**
#### What does this PR do?
 reset password
#### How should this be manually tested?
after cloning it run yarn start
#### What are the relevant pivotal tracker stories?
182201525

### CODE REVIEW

**Comment by ericus123** [comment]
@uwishema11 rebase please

**Comment by didasmbalanya** [comment]
Please make sure your commit messages reflect the changes you are implementing

**Review by ericus123 — APPROVED** [review]

**Comment by ericus123** [comment]
@uwishema11 please rebase

**Review by didasmbalanya — CHANGES_REQUESTED** [review]
Good work so far. works well

Needs a rebase.
Also after a user successfully updates the password and you display the confirmation message, use the `setTimeout` function to redirect the user back to the login page after 5 seconds

**Comment by didasmbalanya** [comment]
Screen Shot 2022-08-30 at 13 40 47

After a successfully password reset please redirect to login page @uwishema11

**Review by didasmbalanya — APPROVED** [review]

**Review by didasmbalanya — APPROVED** [review]

**Pull request merged**
